# Generated by Django 2.2.1 on 2019-05-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190524_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gb',
            field=models.CharField(max_length=16),
        ),
    ]
