# Generated by Django 2.2.1 on 2019-05-26 01:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_ratings'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratings',
            unique_together={('game', 'user')},
        ),
    ]
