# Generated by Django 2.2.1 on 2019-05-29 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190525_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gb',
            new_name='igdb',
        ),
    ]
