# Generated by Django 2.2.3 on 2019-07-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_auto_20190715_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='entry_type',
            field=models.CharField(choices=[('F', 'Finished'), ('S', 'Started'), ('P', 'Played'), ('A', 'Abandoned')], default='F', max_length=1),
        ),
    ]
