# Generated by Django 2.2.3 on 2019-07-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_auto_20190716_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='platform',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
