# Generated by Django 2.2.1 on 2019-06-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='igdb',
            field=models.IntegerField(),
        ),
    ]
