# Generated by Django 2.2.3 on 2019-07-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover_id',
            field=models.CharField(max_length=255),
        ),
    ]
