# Generated by Django 2.2.3 on 2019-07-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_cover_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
