# Generated by Django 2.2.3 on 2019-07-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20190710_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_id',
            field=models.CharField(max_length=255),
        ),
    ]
