# Generated by Django 2.2.3 on 2019-07-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20190710_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='backdrop_id',
            field=models.CharField(max_length=255),
        ),
    ]
