# Generated by Django 2.2.3 on 2019-07-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_game_backdrop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='backdrop_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
