# Generated by Django 2.2.1 on 2019-05-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190524_2144'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='games',
        ),
        migrations.AddField(
            model_name='customuser',
            name='games',
            field=models.ManyToManyField(to='api.Game'),
        ),
    ]
