# Generated by Django 2.2.1 on 2019-05-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_game_name'),
        ('users', '0002_auto_20190524_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='games',
        ),
        migrations.AddField(
            model_name='customuser',
            name='liked',
            field=models.ManyToManyField(related_name='liked_games', to='api.Game'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='played',
            field=models.ManyToManyField(related_name='played_games', to='api.Game'),
        ),
    ]
