# Generated by Django 2.2.1 on 2019-05-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_game_name'),
        ('users', '0003_auto_20190524_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='backlog',
            field=models.ManyToManyField(related_name='backlog', to='api.Game'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist', to='api.Game'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='liked',
            field=models.ManyToManyField(related_name='liked', to='api.Game'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='played',
            field=models.ManyToManyField(related_name='played', to='api.Game'),
        ),
    ]
