# Generated by Django 2.2.1 on 2019-05-30 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190528_1923'),
        ('users', '0004_auto_20190525_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='api.Game'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='followers',
            field=models.ManyToManyField(related_name='_customuser_followers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(related_name='_customuser_following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
