# Generated by Django 2.2.3 on 2019-07-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190615_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gravatar',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
